# Volcano Plot Script (R/ggplot2)
# Generated by volcano-plot-script

library(ggplot2)
library(dplyr)

# Read data
data <- read.csv("references/example_deg_data.csv")

# Parameters
log2fc_col <- "log2FoldChange"
pvalue_col <- "padj"
gene_col <- "gene"
log2fc_thresh <- 1.0
pvalue_thresh <- 0.05

# Process data
data$negLog10_pvalue <- -log10(data[[pvalue_col]])

data <- data %>%
  mutate(regulation = case_when(
    .data[[pvalue_col]] < pvalue_thresh & .data[[log2fc_col]] > log2fc_thresh ~ "up",
    .data[[pvalue_col]] < pvalue_thresh & .data[[log2fc_col]] < -log2fc_thresh ~ "down",
    TRUE ~ "ns"
  ))

# Create plot
p <- ggplot(data, aes(x=.data[[log2fc_col]], y=negLog10_pvalue, color=regulation)) +
  geom_point(alpha=0.6, size=1.5) +
  scale_color_manual(values=c("up"="#E74C3C", 
                              "down"="#3498DB", 
                              "ns"="#95A5A6"),
                     labels=c("up"="Upregulated", 
                              "down"="Downregulated", 
                              "ns"="Not significant")) +
  geom_hline(yintercept=-log10(pvalue_thresh), linetype="dashed", color="gray") +
  geom_vline(xintercept=c(-log2fc_thresh, log2fc_thresh), linetype="dashed", color="gray") +
  labs(x="Log2 Fold Change", y="-Log10 Adjusted P-value", title="Volcano Plot") +
  theme_minimal() +
  theme(legend.position="bottom")

# Save plot
ggsave("assets/example_volcano.png", p, width=10, height=8, dpi=300)
print(paste("Plot saved to:", "assets/example_volcano.png"))
