# PyMOL Ray-Traced Rendering Script
# Generated by 3D Molecule Ray-tracer
# Target: 1mbn
# Preset: cover

from pymol import cmd

# Load structure
fetch 1mbn, async=0

# Basic settings
bg_color white
set antialias, 4
set orthoscopic, 1
set valence, 0

# Representation settings
hide everything
show cartoon
set cartoon_fancy_helices, 1
set cartoon_fancy_sheets, 1
set cartoon_smooth_loops, 1
set cartoon_side_chain_helper, 1

# Color scheme
util.cbc()  # Color by chain

# Lighting configuration
set ambient, 0.15
set direct, 0.6
set reflect, 0.7
set spec_power, 80

# Three-point lighting setup
set light_count, 3
set light1, [0.5, 0.5, -1.0]  # Key light
set light2, [-0.8, 0.3, -0.5]  # Fill light
set light3, [0.2, -0.9, -0.3]  # Rim light

# Advanced effects
# Ambient occlusion
set ambient_occlusion_mode, 1
set ambient_occlusion_scale, 1.0
set ambient_occlusion_smooth, 1
# Soft shadows
set ray_shadows, 1
set ray_shadow_fudge, 0.1
# Volumetric fog (depth cueing)
set depth_cue, 1
set fog, 0.1
set fog_start, 0.5

# Depth of Field settings
set ray_trace_mode, 1
set ray_trace_gain, 0.0100
set dof_mode, 1
set dof_aperture, 2.0
center
set dof_focus, 0  # Focus on center

# Camera setup
reset
zoom complete=1

# Ray tracing and output
set ray_trace_fog, 1
set ray_trace_frames, 0
ray 3000, 3000
png cover_render.png, dpi=300

print("Rendering complete: cover_render.png")
