# PyMOL Ray-Traced Rendering Script
# Generated by 3D Molecule Ray-tracer
# Target: 1mbn
# Preset: standard

from pymol import cmd

# Load structure
fetch 1mbn, async=0

# Basic settings
bg_color white
set antialias, 2
set orthoscopic, 1
set valence, 0

# Representation settings
hide everything
show cartoon
set cartoon_fancy_helices, 1
set cartoon_fancy_sheets, 1
set cartoon_smooth_loops, 1
set cartoon_side_chain_helper, 1

# Color scheme
util.cbc()  # Color by chain

# Lighting configuration
set ambient, 0.2
set direct, 0.5
set reflect, 0.5
set spec_power, 55

# Advanced effects
set ray_shadows, 0
set depth_cue, 0
set fog, 0

# Depth of Field settings
set dof_mode, 0  # DOF disabled
set ray_trace_mode, 1
set ray_trace_gain, 0.01

# Camera setup
reset
zoom complete=1

# Ray tracing and output
set ray_trace_fog, 1
set ray_trace_frames, 0
ray 2400, 2400
png standard_render.png, dpi=300

print("Rendering complete: standard_render.png")
